In [4]:
import numpy as np
np.__version__


'1.19.0'

In [5]:
np1=np.array([1,2,3])
np2=np.array([3,4,5])

In [6]:
print(np1+np2)

[4 6 8]


In [7]:
print(np1.ndim,np1.shape,np1.dtype) #一維陣列, 三個元素, 資料型別

1 (3,) int32


In [8]:
np3 = np.array([1, 2, 3, 4, 5, 6])
np3=np3.reshape([2,3])
print(np3.ndim,np3.shape,np3.dtype)

2 (2, 3) int32


In [9]:
print(np3)

[[1 2 3]
 [4 5 6]]


In [10]:
np3 = np3.astype('int64')
print(np3.dtype)

int64


In [11]:
np3=np.array([1,2,3,4,5,6])
print(np3[2])

3


In [12]:
np3 = np3.reshape([2,3])
print(np3[1,0])

4


In [14]:
np3=np.array([1,2,3,4,5,6])
print(np3>3)

[False False False  True  True  True]


In [15]:
np3 = np3.reshape([2,3])
print(np3.sum(axis=1))

[ 6 15]


In [18]:
arr=np.arange(10)

In [19]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr[5:8]

array([5, 6, 7])

In [22]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0][2]

3

In [23]:
arr2d[0,2]

3

In [24]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [25]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [26]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr2d[:2,:1]

array([[1],
       [4]])

In [28]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [32]:
data = np.random.randn(7,4)
data

array([[ 1.93059051, -1.98810474,  0.37071378, -1.10575454],
       [-1.25887909, -0.32930867,  1.25507338, -0.38863276],
       [ 0.0885912 ,  0.46193055, -1.83516175, -0.77823   ],
       [ 1.28027579,  1.26937354,  0.14128081, -0.57187645],
       [ 1.66855141,  0.89684696, -1.21131922, -0.12262448],
       [ 1.12360286, -1.47422109, -1.15899073,  2.16173169],
       [-0.01479369, -0.89450749, -0.36849746, -0.48819406]])

In [34]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'],dtype='<U4')

In [35]:
names =='Bob'

array([ True, False, False,  True, False, False, False])

In [36]:
data[names == 'Bob']

array([[ 1.93059051, -1.98810474,  0.37071378, -1.10575454],
       [ 1.28027579,  1.26937354,  0.14128081, -0.57187645]])